apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: azurequeue-function
  triggers:
  - type: azure-queue
    metadata:
      queueName: functionsqueue
      accountName: storage-account-name
      connectionFromEnv: STORAGE_CONNECTIONSTRING_ENV_NAME
      queueLength: "5"
      cloud: Private
      endpointSuffix: queue.local.azurestack.external
    authenticationRef:
        name: azure-queue-auth